// <auto-generated />
namespace TruckCheckUp.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DroppedTruckInspectionFKintableDriverCommentandaddedTicketNumberfieldtochainbothtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DroppedTruckInspectionFKintableDriverCommentandaddedTicketNumberfieldtochainbothtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201904290254376_Dropped TruckInspection FK in table DriverComment and added TicketNumber field to chain both tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
