// <auto-generated />
namespace TruckCheckUp.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MaderequiredfieldforCategoryIdFKTablePartCatalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaderequiredfieldforCategoryIdFKTablePartCatalog));
        
        string IMigrationMetadata.Id
        {
            get { return "201904150024521_Made required field for CategoryId FK Table PartCatalog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
