// <auto-generated />
namespace TruckCheckUp.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DroppedStatusDatecolumnfromtableSituation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DroppedStatusDatecolumnfromtableSituation));
        
        string IMigrationMetadata.Id
        {
            get { return "201907022046442_Dropped StatusDate column from table Situation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
